# -*- coding: utf-8 -*-
"""modelling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThBYnHev-dYGe9ma9Vn3NMPCtw7wi70i
"""

import os
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

# Hubungkan ke DagsHub
os.environ['MLFLOW_TRACKING_USERNAME'] = 'amar.luthfi18154'
os.environ['MLFLOW_TRACKING_PASSWORD'] = '83571676d8095a3920f1aa4957eb2461370a6a6c'
mlflow.set_tracking_uri('https://dagshub.com/amar.luthfi18154/SMSML_Amar-Luthfi.mlflow')
mlflow.set_experiment('Credit Scoring')

def run_baseline_model():
    # Mengambil data
    data_dir = "dataset_preprocessing"

    X_train = pd.read_csv(f"{data_dir}/X_train_processed.csv")
    X_test = pd.read_csv(f"{data_dir}/X_test_processed.csv")
    y_train = pd.read_csv(f"{data_dir}/y_train_processed.csv").values.ravel()
    y_test = pd.read_csv(f"{data_dir}/y_test_processed.csv").values.ravel()

    mlflow.sklearn.autolog()

    # Mulai Run untuk Baseline
    with mlflow.start_run(run_name="Baseline_Model"):
        # Parameter Dasar (Baseline)
        params = {"n_estimators": 50, "max_depth": 3, "random_state": 42}
        mlflow.log_params(params)

        # Training
        model = RandomForestClassifier(**params)
        model.fit(X_train, y_train)

        # Evaluasi
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        # Log Metrik
        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("f1_score", f1)

        # Log Model Baseline
        mlflow.sklearn.log_model(model, "baseline_model")

        print(f"[BASELINE SUKSES] Model Dasar Selesai. Akurasi: {acc:.4f}")

if __name__ == "__main__":
    run_baseline_model()