# -*- coding: utf-8 -*-
"""modelling_tuning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jb6BYpviaUwJ71DMMDb1JNPhIFbOylx0
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
import mlflow
import mlflow.sklearn

def run_tuning_model(data_dir):
    # Hubungkan ke DagsHub
    os.environ['MLFLOW_TRACKING_USERNAME'] = 'amar.luthfi18154'
    os.environ['MLFLOW_TRACKING_PASSWORD'] = '83571676d8095a3920f1aa4957eb2461370a6a6c'
    mlflow.set_tracking_uri('https://dagshub.com/amar.luthfi18154/SMSML_Amar-Luthfi.mlflow')
    mlflow.set_experiment('Credit Scoring Tuning')

    # Memuat Data Preprocessing
    X_train = pd.read_csv(os.path.join(data_dir, "X_train_processed.csv"))
    X_test = pd.read_csv(os.path.join(data_dir, "X_test_processed.csv"))
    y_train = pd.read_csv(os.path.join(data_dir, "y_train_processed.csv")).values.ravel()
    y_test = pd.read_csv(os.path.join(data_dir, "y_test_processed.csv")).values.ravel()

    # Mengaktifkan Autolog MLflow untuk Hyperparameter Tuning
    # max_tuning_runs=None mencatat seluruh kombinasi parameter sebagai anak run (child runs)
    mlflow.sklearn.autolog(max_tuning_runs=None)

    # Inisialisasi Model Baseline & Parameter Grid
    rf = RandomForestClassifier(random_state=42)
    param_grid = {
        'n_estimators': [50, 100],
        'max_depth': [5, 10],
        'min_samples_split': [2, 5]
    }

    # Eksekusi Grid Search
    grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='f1', n_jobs=-1)

    # Membuka Parent Run di MLflow untuk menaungi proses Tuning
    with mlflow.start_run(run_name="Hyperparameter_Tuning_RF") as parent_run:
        print("Memulai proses Grid Search...")
        grid_search.fit(X_train, y_train)

        # Mengambil model terbaik hasil tuning
        best_model = grid_search.best_estimator_
        best_params = grid_search.best_params_

        # Prediksi Menggunakan Model Terbaik
        y_pred = best_model.predict(X_test)

        # Evaluasi Metrik Akhir
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        print(f"Akurasi Terbaik: {acc:.4f}")
        print(f"F1-Score Terbaik: {f1:.4f}")
        print(f"Parameter Terbaik: {best_params}")

        # Manual Logging untuk Metrik Utama Model Terbaik (Parent Run)
        mlflow.log_metrics({
            "best_accuracy": acc,
            "best_f1_score": f1
        })

        # MANAJEMEN ARTEFAK

        # --- ARTEFAK 1: Best Confusion Matrix Plot ---
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(6, 5))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=['Non-Defaulter', 'Defaulter'],
                    yticklabels=['Non-Defaulter', 'Defaulter'])
        plt.title('Best Model Confusion Matrix')
        plt.ylabel('Actual')
        plt.xlabel('Predicted')
        plt.tight_layout()

        plot_path = "best_confusion_matrix.png"
        plt.savefig(plot_path)
        plt.close()

        # Upload Artefak 1 ke MLflow/DagsHub
        mlflow.log_artifact(plot_path)
        print("Artefak 1 (Confusion Matrix) berhasil diunggah!")

        # --- ARTEFAK 2: Feature Importance Plot (Tambahan Tambah Poin) ---
        importances = best_model.feature_importances_
        indices = np.argsort(importances)[::-1]

        # Mengambil 10 fitur teratas untuk digambar ke dalam grafik
        top_n = min(10, len(importances))

        plt.figure(figsize=(10, 5))
        plt.title("Top Feature Importances (Best Model)")
        plt.bar(range(top_n), importances[indices[:top_n]], align="center", color='skyblue')
        plt.xlabel("Feature Index")
        plt.ylabel("Importance")
        feature_names = X_train.columns
        plt.xticks(range(top_n), [feature_names[i] for i in indices[:top_n]], rotation=45, ha='right')
        plt.tight_layout()

        feat_path = "feature_importances.png"
        plt.savefig(feat_path)
        plt.close()

        # Upload Artefak 2 ke MLflow/DagsHub
        mlflow.log_artifact(feat_path)
        print("Artefak 2 (Feature Importance Plot) berhasil diunggah!")

        # Pembersihan File Gambar Lokal di Runtime Colab
        if os.path.exists(plot_path):
            os.remove(plot_path)
        if os.path.exists(feat_path):
            os.remove(feat_path)

        print("Eksperimen Tuning selesai dan berhasil dicatat di DagsHub!")

if __name__ == '__main__':
    # Lokasi folder preprocessing Anda di Google Colab saat ini
    DATA_DIRECTORY = "dataset_preprocessing"

    # Jalankan fungsi utama
    run_tuning_model(DATA_DIRECTORY)